### ISSUE TITLE
Configurable app dashboards

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/next-graphite-dashboard#84]
Some apps (e.g. spoor-consumer, myft-email) need additional/different graphs

We could add the ability to override & augment dashboards with simple yaml config

e.g

```yaml
-
  appName: spoor-consumer
  includeDefaultGraphs: false
  graphs: 
    -
      title: keen-pipeline
      graphiteUrl: blahblah
```
